server:
  port: 9102
  servlet:
    context-path: /

dubbo:
  application:
    name: consumer
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880